### ISSUE TITLE
Support custom ASB connection string keys

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.AzureFunctions.Worker.ServiceBus#29]
Currently `NServiceBusTriggerFunction` doesn't support configuration of a different connection string (key) and assumes the default connection string key for Azure Service Bus triggers (`AzureWebJobsServiceBus`). This can become an issue when the connection string is provided on a different key name as this would require a custom trigger definition and a matching transport configuration.

Originally raised in https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/issues/28

**Comment by timbussmann** [comment]
Imo this is good enough if it is possible to load the connection string from a custom source, e.g. environment variables (kinda standard for Functions atm) or alternatively from `IConfiguration`.

**Comment by danielmarbach** [comment]
Just came out of a customer call with @timbussmann. Once you start using different keys it becomes quite complex because you need to write boilerplate code that gets the env variables and passes it to the API that accepts the connection string, or you have to load the new key and assign it to the standard connection key. 

Having support for custom keys would simplify that boilerplate code.

**Comment by andreasohlund** [comment]
This has been shipped in 5.1 see https://docs.particular.net/nservicebus/hosting/azure-functions-service-bus/#configuration-servicebus-connection
