### ISSUE TITLE
"Cannot convert input parameter userProperties to type IDictionary from type String"

### ISSUE THREAD

**Issue by johnkors** [Particular/NServiceBus.AzureFunctions.Worker.ServiceBus#400]
#### Description
I haven't touched the production environment for a good 1-2 years, and suddenly started seeing a huge spike of errors. 

Spike:
```
traces
| where message startswith "Trigger Details: MessageId: 7d697106-0699-48b6-aafe-99e1b59d681d"
| count 
```
=> 857093 

Any ideas?

Usage:
```cs
[assembly: NServiceBusTriggerFunction("%ENDPOINT_NAME%", TriggerFunctionName = "MyFunctionAutoGenerated")]
```

#### Versions

```xml
"Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" 
"Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0" 
"Microsoft.Azure.Functions.Worker" Version="1.6.0"
"NServiceBus.AzureFunctions.Worker.ServiceBus" Version="2.0.1"
```

### Steps to reproduce

No idea to repro, as this just started appearing in production 3 days ago. Are there any changes on MS end that are not compatible with this package in this version?

### Relevant log output

```shell
Exception: Microsoft.Azure.Functions.Worker.Diagnostics.Exceptions.FunctionInputConverterException: Error converting 1 input parameters for Function 'MyFunctionAutoGenerated': Cannot convert input parameter 'userProperties' to type 'System.Collections.Generic.IDictionary`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' from type 'System.String'.
   at Microsoft.Azure.Functions.Worker.Context.Features.DefaultModelBindingFeature.BindFunctionInput(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Context\Features\DefaultModelBindingFeature.cs:line 70
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
   at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 16
   at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 167
Stack:    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultModelBindingFeature.BindFunctionInput(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Context\Features\DefaultModelBindingFeature.cs:line 70
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
   at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 16
   at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 167
```

**Comment by cquirosj** [comment]
@johnkors looks like an [issue like](https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/issues/70) this was reported a while ago, and it was happening only during retries. Is the sudden spike you see now because many retries are happening? A user reported they were able to see the real reason for the retries after using the workaround mentioned in [this thread](https://discuss.particular.net/t/azure-function-isolated-worker-fails-when-binding-converting-userproperties/2840/2)

A fix for this was introduced on version [2.0.2](https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/releases/tag/2.0.2). The latest version of the package is 4.2.1.

**Comment by johnkors** [comment]
No idea if it's retries, just guessing it is since I see so many log statement on the samme messageId.

Thanks, I'll check what 2.0.2 says.

**Comment by johnkors** [comment]
I haven't configured any retry policy for this NServiceBus endpoint, so I would assume it was going to fallback to the defaults. Yet, for this specific issue, it looks like it ended up in a retry-loop for some reason. Each message ended up being retried in a loop. I only got aware of this issue due to the function piling up logs in App Insights (this bug cost us 4 digits in Azure Insights costs) and it went over the default quota of 100 GB logs. Do you have any explanation into why it would go into a loop, when no retry policy has been configured? Any logical reason for it..=?

**Comment by cquirosj** [comment]
If the defaults have not been disabled ([1](https://docs.particular.net/nservicebus/recoverability/configure-immediate-retries#disabling), [2](https://docs.particular.net/nservicebus/recoverability/configure-delayed-retries#disabling-through-code)), then the number of default retries will be used, which is 5 for immediate and 3 for delayed.

The immediate retry mechanism is implemented by making the message available for consumption again, so that the endpoint can process it again without any delay. [The bug in question](https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/issues/70) happens while processing retries. Since the serialization error is happening while instantiating the server-less function, the message handler never gets a chance to process the message being retried again, preventing the default policy from ever reaching the default configured value.

**Comment by johnkors** [comment]
Sure, got it.

We created this subscription (ASB queue) using the NServiceBus tooling (`NServiceBus.Transport.AzureServiceBus.CommandLine`) which creates queues with `int.MaxValue` as the Max Delivery Count:

https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/blob/a5933e6796b529ad5e95547d7de413f901374821/src/CommandLine/Queue.cs#L12-L19

So both the bug in `NServiceBus.AzureFunctions.Worker.ServiceBus` 2.0.1 and a `int.MaxValue` default in the tooling led to the "infinite" loop when used with functions, and a rather larger bill for us. 

Thanks for clarifying.

**Comment by cquirosj** [comment]
I am sorry that the combination of circumstances led to a hefty bill. Thank you very much for pointing out the MaxDeliveryCount aspect of the command line tool in this situation.  

Have you made the required changes, including the update of the package and tested that retries will now behave as expected? If so, can this issue be closed? I can open a new issue focused on addressing the MaxDeliveryCount = int.MaxValue aspect and ask for your feedback once it is created.

**Comment by johnkors** [comment]
Yeah, updated the package - but rather hard to repro something going wrong in between ASB and NServiceBus, so I'll just have to trust that the update works better. Unless you have some pointers how to do it.

I've also reduced max limits in Azure, and added more cost alerts - so at least that's something.

Closing this.

**Comment by cquirosj** [comment]
@johnkors,

> but rather hard to repro something going wrong in between ASB and NServiceBus

It would be a matter of checking if any retry has been processed after the package was updated. Confirming that now the exception that you mentioned is no longer shown in the logs, but rather the exception from the business logic within the message handler that triggered the retry. 

If no retries have happened, maybe you can temporarily deploy a version with a condition that will result in a retry. 

If that is something feasible, depending on the retry policy you left configured, you should see the retries being exhausted, let's say 5 immediate retries and 3 delayed retries and then the message being sent to the error queue. In all the retries, the exception from the business logic in the handler is what should be logged and not the exception you shared when this issue was first opened.
