### ISSUE TITLE
Broken since Microsoft.Azure.Functions.Worker.Sdk 1.16.0+

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureFunctions.Worker.ServiceBus#428]
#### Description

Function handler is not resolved when using [Microsoft.Azure.Functions.Worker.Sdk](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk) version 1.16.0 or newer

#### Expected behavior

At startup it should show `NServiceBusFunctionEndpointTrigger-ASBWorkerEndpoint: serviceBusTrigger`.

```
Azure Functions Core Tools
Core Tools Version:       4.0.5455 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.27.5.21554

[2023-12-13T11:16:55.899Z] Found S:\docs.particular.net\samples\azure-functions\service-bus-worker\ASBFunctionsWorker_5\AzureFunctions.ASBTrigger.Worker\AzureFunctions.ASBTrigger.Worker.csproj. Using for user secrets file configuration.

Functions:

        HttpSender: [GET,POST] http://localhost:7071/api/HttpSender

        NServiceBusFunctionEndpointTrigger-ASBWorkerEndpoint: serviceBusTrigger

For detailed output, run func with --verbose flag.
[2023-12-13T11:16:57.256Z] Worker process started and initialized.
[2023-12-13T11:17:01.811Z] Host lock lease acquired by instance ID '0000000000000000000000005EC04FB1'.
```

#### Actual behavior

```
Azure Functions Core Tools
Core Tools Version:       4.0.5455 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.27.5.21554

[2023-12-13T11:20:28.121Z] Found S:\docs.particular.net\samples\azure-functions\service-bus-worker\ASBFunctionsWorker_5\AzureFunctions.ASBTrigger.Worker\AzureFunctions.ASBTrigger.Worker.csproj. Using for user secrets file configuration.
[2023-12-13T11:20:29.487Z] Worker process started and initialized.

Functions:

        HttpSender: [GET,POST] http://localhost:7071/api/HttpSender

For detailed output, run func with --verbose flag.
[2023-12-13T11:20:34.552Z] Host lock lease acquired by instance ID '0000000000000000000000005EC04FB1'.
```

#### Versions

Please list the version of the relevant packages or applications in which the bug exists.        

- 5.0.0-alpha.1
- 4.2.1
- 3.1.9

Untested for older major versions

### Steps to reproduce

1. Use sample https://docs.particular.net/samples/azure-functions/service-bus-worker/?
2. Observe that is using Microsoft.Azure.Functions.Worker.Sdk Version 1.* and that is will use 1.16.1
3. When run is isn't outputting `NServiceBusFunctionEndpointTrigger-ASBWorkerEndpoint: serviceBusTrigger` and will not trigger the handler when there are messages.

#### Workarounds

Downgrade to version 1.15.1 and do a full rebuild.

**Comment by danielmarbach** [comment]
FYI this is related to https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/issues/418

**Comment by danielmarbach** [comment]
[This would be the "workaround"](https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/pull/420) but @bording and I debated whether we should do this fix since the underlying issues we are seeing here are coming from a breaking change in the SDK.

**Comment by danielmarbach** [comment]
The issue seems to come from the new function metadata provider source generator. It appears that the source generator runs before the function endpoint trigger has the possibility to run, which then doesn't generate the necessary function metadata to be able to discover the hosted functions.

By switching back to the previous way of discovering functions by adding

```xml
  <PropertyGroup>
    <FunctionsEnableWorkerIndexing>false</FunctionsEnableWorkerIndexing>
  </PropertyGroup>
```

the functions start working again even with SDK 1.19.0 and higher.

**Comment by danielmarbach** [comment]
Another current workaround is to copy the source generated trigger function locally and then disable the source generator by adding the following target to the project

```xml
  <Target Name="DisableAnalyzers"
          BeforeTargets="CoreCompile">
    <ItemGroup>
      <Analyzer Remove="@(Analyzer)"
                Condition="'%(Filename)' == 'NServiceBus.AzureFunctions.Worker.SourceGenerator'"/>
    </ItemGroup>
  </Target>
```

**Comment by danielmarbach** [comment]
> The issue seems to come from the new function metadata provider source generator. It appears that the source generator runs before the function endpoint trigger has the possibility to run, which then doesn't generate the necessary function metadata to be able to discover the hosted functions.
> 
> By switching back to the previous way of discovering functions by adding
> 
> ```
>   <PropertyGroup>
>     <FunctionsEnableWorkerIndexing>false</FunctionsEnableWorkerIndexing>
>   </PropertyGroup>
> ```
> 
> the functions start working again even with SDK 1.19.0 and higher.

Unfortunately, it turned out there is more needed. It is required to disable the metadadata generator AND the executor generator to make the source generated function being picked up. But currently there is also a bug in the SDK targets file [which causes the actual property to disable the metadata source generator to be coupled to `FunctionsEnableWorkerIndexing`](https://github.com/Azure/azure-functions-dotnet-worker/issues/2209). To make things properly work the workaround is to add

```xml
  <PropertyGroup>
    <FunctionsEnableMetadataSourceGen>false</FunctionsEnableMetadataSourceGen>
    <FunctionsEnableExecutorSourceGen>false</FunctionsEnableExecutorSourceGen>
    <FunctionsEnableWorkerIndexing>false</FunctionsEnableWorkerIndexing>
  </PropertyGroup>
```

once the issue is addressed by [merging the PR I've added](https://github.com/Azure/azure-functions-dotnet-worker/pull/2210) the workaround boils down to

```xml
  <PropertyGroup>
    <FunctionsEnableMetadataSourceGen>false</FunctionsEnableMetadataSourceGen>
    <FunctionsEnableExecutorSourceGen>false</FunctionsEnableExecutorSourceGen>
  </PropertyGroup>
```

We will be shipping a properties file as part of the nuget package to make the source generator work again until the source generated code from microsoft is more extendable for our scenario.
